version: '3'
services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - analysis_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./csv_data:/csv_data
      - ./sql:/docker-entrypoint-initdb.d

  jupyter:
    image: jupyter:recsys
    container_name: jupyter_lab
    ports:
      - "8888:8888"
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    volumes:
      - ./notebooks:/notebooks
    networks:
      - analysis_network
    depends_on:
      - postgres
      
networks:
  analysis_network:
    driver: bridge

volumes:
  postgres_data:
